name: vovinamfitness
favicon: null
layout_spectrum: 0.8843402434140444
typography_spectrum: 0.7580984844826162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffce'
    - '#0607d4'
    - '#847e65'
    - '#44433c'
    - '#c94445'
  brandStrength: 1
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 1
purpose: []
